name: task_manager
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http:
  provider:
  device_preview:
  shimmer:
  fluttertoast:
  google_fonts:
  flutter_svg:
  intl:
  pin_code_fields:
  logger:
  email_validator:
  google_nav_bar:
  percent_indicator:
  image_picker:
  introduction_screen:
  flutter_screenutil:
  shared_preferences:
  mime:
  dio:
  get: ^4.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
    - assets/icons/
    - assets/images/



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
